# Development overrides - adds build contexts for local development
services:
  zotprime-db:
#    image: mysql:5.6
    build:
      context: ./stack/db
      dockerfile: db.Dockerfile
#    command: --default-authentication-plugin=mysql_native_password
#    ulimits:
#      nofile:
#         soft: 262144
#         hard: 262144

  zotprime-elasticsearch:
    build:
      context: ./stack/elasticsearch
      dockerfile: es.Dockerfile
#      - cluster.routing.allocation.disk.threshold_enabled=false 
#      - bootstrap.memory_lock=true
#      - cluster.routing.allocation.disk.watermark.flood_stage=500mb
#    sysctls:
#      - vm.max_map_count=262144
#    cap-add:
#      - SYS_ADMIN
#    privileged: true
#    user: root
#    command: 
#      - /bin/bash
#      - -c
#      - |
#       sysctl -w vm.max_map_count=262144 &&
#       su elasticsearch -c bin/elasticsearch
#    command:
#      - /bin/bash
#      - -c
#      - |
#       sysctl -w vm.max_map_count=262144 && 
#       su elasticsearch -c bin/es-docker

  zotprime-redis:
    build:
      context: ./stack/redis
      dockerfile: r.Dockerfile
 #   privileged: true
 #    user: root
 #    sysctls:
 #      - sysctl vm.overcommit_memory=1

  zotprime-memcached:
    build:
      context: ./stack/memcached
      dockerfile: m.Dockerfile

  zotprime-localstack:
    build:
      context: ./stack/localstack
      dockerfile: ls.Dockerfile

  zotprime-minio:
    build:
      context: ./stack/minio
      dockerfile: minio.Dockerfile
#      - "8082:9000"

  zotprime-miniomc:
    build:
      context: ./stack/minio
      dockerfile: miniomc.Dockerfile
#    entrypoint: >
#         /bin/sh -c "
#         /usr/bin/mc config host add minio http://zotprime-minio:9000 ${MINIOROOTUSER} ${MINIOROOTPASSWORD}; 
#         exec mc admin trace -v -a minio;
#         "
#          exec sleep inf;

  zotprime-dataserver:
    build:
      context: ./stack/dataserver
      dockerfile: ds.Dockerfile
#    extra_hosts:
#      - "zotero.localhost:127.0.0.1"
#      - "zotero-fulltext.localhost:127.0.0.1"
#      - "8082:8082"
#      - "9000:9000"

  zotprime-tinymceclean:
    build:
      context: ./stack/tinymce-clean-server
      dockerfile: tmcs.Dockerfile

  zotprime-streamserver:
    build:
      context: ./stack/stream-server
      dockerfile: sts.Dockerfile
#      - "./docker/stream-server/default.js:/usr/src/app/config/default.js:ro"

  zotprime-phpmyadmin:
    build:
      context: ./stack/phpmyadmin
      dockerfile: pa.Dockerfile