apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-admin-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  admin-username: {{ required "adminUser.username is required" .Values.adminUser.username }}
  admin-password: {{ required "adminUser.password is required" .Values.adminUser.password }}
  admin-email: {{ required "adminUser.email is required" .Values.adminUser.email }}
type: Opaque
