apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-db-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  mysql-root-password: {{ required "dbSecret.mysqlRootPassword is required" .Values.dbSecret.mysqlRootPassword }}
  mysql-password: {{ required "dbSecret.mysqlPassword is required" .Values.dbSecret.mysqlPassword }}
type: Opaque