{{- if .Values.zotprimeMinio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    apps: minio
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.minio.type }}
  {{- if .Values.minio.clusterIP }}
  clusterIP: {{ .Values.minio.clusterIP }}
  {{- end }}
  selector:
    apps: zotprime-minio
  ports:
  {{- if .Values.zotprimeMinio.exposeWebUI }}
  - name: minio-ui
    port: 9001
    targetPort: 9001
  {{- end }}
  - name: minio-data
    port: 9000
    targetPort: 9000
  - name: minio-data2
    port: 80
    targetPort: 9000
{{- end }}