apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vpn-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.7.7.10-10.7.7.50
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vpn-pool-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - vpn-pool
