apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-auth-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  auth-salt: {{ required "authSecret.authSalt is required" .Values.authSecret.authSalt }}
  api-super-token-hash: {{ required "authSecret.apiSuperTokenHash is required" .Values.authSecret.apiSuperTokenHash }}
  app-key: {{ required "authSecret.appKey is required" .Values.authSecret.appKey }}
type: Opaque
