{{- if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-basic-auth
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  auth: {{ required "basicAuth.htpasswd is required when basicAuth.enabled is true" .Values.basicAuth.htpasswd }}
type: Opaque
{{- end }}
