apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-blob-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  aws-secret-access-key: {{ required "blobSecret.awsSecretAccessKey is required" .Values.blobSecret.awsSecretAccessKey }}
type: Opaque
