apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-db-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  mariadb-root-password: {{ required "dbSecret.mariadbRootPassword is required" .Values.dbSecret.mariadbRootPassword }}
  mariadb-password: {{ required "dbSecret.mariadbPassword is required" .Values.dbSecret.mariadbPassword }}
type: Opaque