apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    apps: mariadb
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: {{ .Values.mariadb.type }}
  selector:
    apps: zotprime-db
  ports:
	{{- .Values.mariadb.ports | toYaml | nindent 2 -}}