apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-minio-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  minio-root-password: {{ required "minioSecret.minioRootPassword is required" .Values.minioSecret.minioRootPassword }}
type: Opaque