{{- if .Values.zotprimeMinio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    apps: minio
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.type }}
  {{- if .Values.minio.clusterIP }}
  clusterIP: {{ .Values.minio.clusterIP }}
  {{- end }}
  selector:
    apps: zotprime-minio
  ports:
	{{- .Values.minio.ports | toYaml | nindent 2 -}}
{{- end }}