{{- if .Values.webPortal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-portal-secret
  labels:
    {{- include "zotprime-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
type: Opaque
data:
  sessionSecret: {{ .Values.webPortalSecret.sessionSecret | b64enc | quote }}
{{- end }}
