apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-webadmin-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  webadmin-password: {{ required "webAdmin.password is required" .Values.webAdmin.password }}
type: Opaque
