apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-zotero-admin-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  zotero-admin-password: {{ required "zoteroSecret.adminPassword is required" .Values.zoteroSecret.adminPassword }}
type: Opaque
