apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-zotprime-ingress-http
  labels:
    apps: zotprime-ingress-http
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tls.enabled }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - secretName: {{ include "zotprime-k8s.fullname" . }}-tls
    hosts:
    {{- if and (not .Values.basicAuth.enabled) .Values.zotprimeMinio.exposeWebUI }}
    - {{ .Values.ingressHostnames.minios3Web }}
    {{- end }}
    {{- if and (not .Values.basicAuth.enabled) .Values.zotprimePhpmyadmin.enabled }}
    - {{ .Values.ingressHostnames.phpmyadmin }}
    {{- end }}
    - {{ .Values.ingressHostnames.minios3Data }}
    - {{ .Values.ingressHostnames.api }}
  {{- end }}
  rules:
  {{- if and (not .Values.basicAuth.enabled) .Values.zotprimeMinio.exposeWebUI }}
  - host: {{ .Values.ingressHostnames.minios3Web }}
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              name: minio-ui
        path: /
        pathType: Prefix
  {{- end }}
  {{- if and (not .Values.basicAuth.enabled) .Values.zotprimePhpmyadmin.enabled }}
  - host: {{ .Values.ingressHostnames.phpmyadmin }}
    http:
      paths:
      - backend:
          service:
            name: phpmyadmin
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- end }}
  - host: {{ .Values.ingressHostnames.minios3Data }}
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              name: minio-data
        path: /
        pathType: Prefix
  - host: {{ .Values.ingressHostnames.api }}
    http:
      paths:
      - backend:
          service:
            name: dataserver
            port:
              name: dataserver-api
        path: /
        pathType: Prefix